<?php

declare(strict_types=1);

namespace Mammatus\Http\Server\Server;

use FastRoute\ConfigureRoutes;
use FastRoute\Dispatcher\Result\Matched;
use FastRoute\Dispatcher\Result\MethodNotAllowed;
use FastRoute\Dispatcher\Result\NotMatched;
use FastRoute\FastRoute;
use FriendsOfReact\Http\Middleware\Psr15Adapter\PSR15Middleware;
use Mammatus\DevApp\Http\Server\FrontendVhost;
use Mammatus\DevApp\Http\Server\HomePageHandler;
use Mammatus\Groups\Contracts\LifeCycleHandler;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Log\LoggerInterface;
use React\Http\HttpServer;
use React\Http\Message\Response;
use React\Http\Middleware\RequestBodyBufferMiddleware;
use React\Http\Middleware\RequestBodyParserMiddleware;
use React\Promise\PromiseInterface;
use React\Socket\SocketServer;
use Throwable;

use function array_map;
use function React\Async\async;
use function React\Async\await;

/**
 * This class is generated by mammatus/http-server, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class Frontend implements LifeCycleHandler
{
    public const string NAME = 'frontend';

    private readonly SocketServer $server;
    private bool $started = false;

    public function __construct(
        private readonly FrontendVhost $vhost,
        private readonly LoggerInterface $logger,
        private readonly HomePageHandler $handlerMammatusDevAppHttpServerHomePageHandler,
    ) {
        $this->server = new SocketServer('0.0.0.0:1337');
    }

    public static function group(): string
    {
        return 'frontend';
    }

    public function start(): void
    {
        if ($this->started) {
            $this->logger->warning('Server already started: {serverName}', ['serverName' => self::NAME]);

            return;
        }

        $this->started = true;
        $this->logger->debug('Starting server: {serverName}', ['serverName' => self::NAME]);
        $dispatcher = FastRoute::recommendedSettings(function (ConfigureRoutes $routes): void {
            $routes->addRoute(
                'GET',
                '/',
                $this->handlerMammatusDevAppHttpServerHomePageHandler->handle(...),
            );
        }, 'frontend')->dispatcher();
        /** @phpstan-ignore argument.type */
        $http = new HttpServer(...[
            async(function (ServerRequestInterface $request, callable $next): ResponseInterface {
                /** @var callable(ServerRequestInterface): PromiseInterface<ResponseInterface> $next */
                $response = await($next($request));

                $this->logger->info(
                    '[{serverName}] {httpMethod} {path} {statusCode}',
                    [
                        'serverName' => self::NAME,
                        'httpMethod' => $request->getMethod(),
                        'path' => $request->getUri()->getPath(),
                        'statusCode' => $response->getStatusCode(),
                    ],
                );

                return $response;
            }),
            //new \WyriHaximus\React\Http\Middleware\ResumeResponseBodyMiddleware(),
            new RequestBodyBufferMiddleware(),
            new RequestBodyParserMiddleware(),
            //new \WyriHaximus\React\Http\Middleware\CustomRequestBodyParsers(),
            ...array_map(static fn (MiddlewareInterface $middleware): callable => new PSR15Middleware($middleware), [...$this->vhost->middleware()]),
            async(static function (ServerRequestInterface $request) use ($dispatcher): ResponseInterface {
                $routeInfo = $dispatcher->dispatch($request->getMethod(), $request->getUri()->getPath());

                /** @phpstan-ignore return.type */
                return match ($routeInfo::class) {
                    NotMatched::class => Response::plaintext(
                        "Not found!\n",
                    )->withStatus(404),
                    MethodNotAllowed::class => Response::plaintext(
                        "Method not allowed!\n",
                    )->withStatus(405),
                    /** @phpstan-ignore callable.nonCallable */
                    Matched::class => ($routeInfo->handler)($request, $routeInfo->variables),
                };
            }),
        ]);
        $http->listen($this->server);
        $http->on('error', function (Throwable $error): void {
            /** @phpstan-ignore psr3.interpolated */
            $this->logger->error($error->getMessage(), ['exception' => $error]);
        });
        $this->logger->debug('Started server: {serverName}', ['serverName' => self::NAME]);
    }

    public function stop(): void
    {
        $this->logger->debug('Stopping server: {serverName}', ['serverName' => self::NAME]);
        $this->server->close();
        $this->logger->debug('Stopped server: {serverName}', ['serverName' => self::NAME]);
    }
}
