<?php declare(strict_types=1);

namespace Mammatus\Http\Server\Server;

/**
 * This class is generated by mammatus/http-server, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class Frontend implements \Mammatus\Groups\Contracts\LifeCycleHandler
{
    public const string NAME = 'frontend';

    private readonly \React\Socket\SocketServer $server;
    private bool $started = false;
        private readonly \Mammatus\Http\Server\WebSocket\WebSocketHub $webSocketHub;
    
    public function __construct(
        private readonly \Mammatus\DevApp\Http\Server\FrontendVhost $vhost,
        private readonly \Psr\Log\LoggerInterface $logger,
        private readonly \Mammatus\Http\Server\WebSocket\Middleware\WebSocketClientAssetMiddleware $webSocketClientAssetMiddleware,
                private readonly \Mammatus\DevApp\Http\Server\DemoWebSocketPageHandler $handlerMammatusDevAppHttpServerDemoWebSocketPageHandler,
                private readonly \Mammatus\DevApp\Http\Server\HomePageHandler $handlerMammatusDevAppHttpServerHomePageHandler,
                private readonly \Mammatus\DevApp\Http\Server\PingHandler $handlerMammatusDevAppHttpServerPingHandler,
                private readonly \Mammatus\DevApp\Http\Server\WebSocketPingHandler $handlerMammatusDevAppHttpServerWebSocketPingHandler,
            ) {
        $this->server = new \React\Socket\SocketServer('0.0.0.0:1337');
                $mapper = new \Mammatus\Http\Server\Server\WebSocket\Hydrators\Frontend();
        $codec = new \Mammatus\Http\Server\WebSocket\WebSocketPayloadCodec($mapper);
        $this->webSocketHub = new \Mammatus\Http\Server\WebSocket\WebSocketHub($codec, 13, 'heartbeat');
                $this->webSocketHub->registerRpc(
            'ping',
            fn (mixed $params, \Psr\Http\Message\ServerRequestInterface $request): mixed => $this->handlerMammatusDevAppHttpServerWebSocketPingHandler->ping($params, $request),
                'Mammatus\DevApp\Http\Server\WebSocketPingParams',
            'Mammatus\DevApp\Http\Server\WebSocketPingResult',
        );
                    }

        public function webSocketHub(): \Mammatus\Http\Server\WebSocket\WebSocketHub
    {
        return $this->webSocketHub;
    }
    
    public static function group(): string
    {
        return 'frontend';
    }

    public function start(): void
    {
        if ($this->started) {
            $this->logger->warning('Server already started: {serverName}', ['serverName' => self::NAME]);
            return;
        }
        $this->started = true;
        $this->logger->debug('Starting server: {serverName}', ['serverName' => self::NAME]);
        $dispatcher = \FastRoute\FastRoute::recommendedSettings(function(\FastRoute\ConfigureRoutes $routes): void {
            $routes->addRoute(
                \Mammatus\Http\Server\Attributes\HttpMethod::GET->value,
                '/',
                $this->handlerMammatusDevAppHttpServerHomePageHandler->handle(...),
                                                );
            $routes->addRoute(
                \Mammatus\Http\Server\Attributes\HttpMethod::GET->value,
                '/demo/websocket',
                $this->handlerMammatusDevAppHttpServerDemoWebSocketPageHandler->handle(...),
                                                );
            $routes->addRoute(
                \Mammatus\Http\Server\Attributes\HttpMethod::GET->value,
                '/ping/{name}',
                /**
                  * PHPStan is right here, `\Mammatus\DevApp\Http\Server\Ping::create` expects a sealed array shape, but we don't know the shape here.
                  * (Given this code is generated.)
                  * @phpstan-ignore argument.type
                  */
                fn (\Psr\Http\Message\ServerRequestInterface $request, array $params): \Psr\Http\Message\ResponseInterface => $this->handlerMammatusDevAppHttpServerPingHandler->handle(\Mammatus\DevApp\Http\Server\Ping::create($request, $params)),
                                                );
                    }, \dirname(__DIR__, 2) . \DIRECTORY_SEPARATOR . 'var' . \DIRECTORY_SEPARATOR . 'fast-route' . \DIRECTORY_SEPARATOR . 'frontend')->dispatcher();
        $http = new \React\Http\HttpServer(...[
            \React\Async\async(function (\Psr\Http\Message\ServerRequestInterface $request, callable $next): \Psr\Http\Message\ResponseInterface {
                /** @var callable(\Psr\Http\Message\ServerRequestInterface): \React\Promise\PromiseInterface<\Psr\Http\Message\ResponseInterface> $next */
                $response = \React\Async\await($next($request));

                $this->logger->info(
                    '[{serverName}] {httpMethod} {path} {statusCode}',
                    [
                        'serverName' => self::NAME,
                        'httpMethod' => $request->getMethod(),
                        'path' => $request->getUri()->getPath(),
                        'statusCode' => $response->getStatusCode(),
                    ],
                );

                return $response;
            }),
            //new \WyriHaximus\React\Http\Middleware\ResumeResponseBodyMiddleware(),
            new \React\Http\Middleware\RequestBodyBufferMiddleware(),
            new \React\Http\Middleware\RequestBodyParserMiddleware(),
            //new \WyriHaximus\React\Http\Middleware\CustomRequestBodyParsers(),
            new \FriendsOfReact\Http\Middleware\Psr15Adapter\PSR15Middleware($this->webSocketClientAssetMiddleware),
            new \Mammatus\Http\Server\WebSocket\Rfc6455UpgradeMiddleware($this->webSocketHub),
            ...array_map(static fn (\Psr\Http\Server\MiddlewareInterface $middleware): callable => new \FriendsOfReact\Http\Middleware\Psr15Adapter\PSR15Middleware($middleware), [...$this->vhost->middleware()]),
            \React\Async\async(function (\Psr\Http\Message\ServerRequestInterface $request) use ($dispatcher): \Psr\Http\Message\ResponseInterface {
                $routeInfo = $dispatcher->dispatch($request->getMethod(), $request->getUri()->getPath());
                /** @phpstan-ignore return.type */
                return match ($routeInfo::class) {
                    \FastRoute\Dispatcher\Result\NotMatched::class => \React\Http\Message\Response::plaintext(
                            "Not found!\n"
                        )->withStatus(404),
                    \FastRoute\Dispatcher\Result\MethodNotAllowed::class => \React\Http\Message\Response::plaintext(
                            "Method not allowed!\n"
                        )->withStatus(405),
                    /** @phpstan-ignore callable.nonCallable */
                    \FastRoute\Dispatcher\Result\Matched::class => ($routeInfo->handler)($request, $routeInfo->variables),
                };
            }),
        ]);
        $http->listen($this->server);
        $http->on('error', function (\Throwable $error): void {
            /** @phpstan-ignore psr3.interpolated */
            $this->logger->error($error->getMessage(), ['exception' => $error]);
        });
        $this->logger->debug('Started server: {serverName}', ['serverName' => self::NAME]);
    }

    public function stop(): void
    {
        $this->logger->debug('Stopping server: {serverName}', ['serverName' => self::NAME]);
        $this->server->close();
        $this->logger->debug('Stopped server: {serverName}', ['serverName' => self::NAME]);
    }
}
