<?php

declare(strict_types=1);

namespace Mammatus\Http\Server\Kubernetes\Helm;

use Mammatus\Groups\Attributes\Group;
use Mammatus\Groups\Type;
use Mammatus\Kubernetes\Events\Helm\Values;
use WyriHaximus\Broadcast\Contracts\Listener;

/**
 * This class is generated by mammatus/http-server, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class ServerValues implements Listener
{
    public function values(Values $values): void
    {
        $values->addToGroup(
            new Group(Type::Daemon, 'healthz'),
            [
                [
                    'helper' => 'mammatus.container.port',
                    'type' => 'container',
                    'arguments' => [
                        'name' => 'healthz',
                        'containerPort' => 9666,
                    ],
                ],
                [
                    'helper' => 'mammatus.container.probe',
                    'type' => 'container',
                    'arguments' => [
                        'liveness' => [
                            'path' => '/probe/liveness',
                            'vhost' => 'healthz',
                        ],
                        'readiness' => [
                            'path' => '/probe/readiness',
                            'vhost' => 'healthz',
                        ],
                        'startUp' => [
                            'path' => '/probe/startup',
                            'vhost' => 'healthz',
                        ],
                    ],
                ],
            ],
        );
    }
}
