<?php declare(strict_types=1);

namespace Mammatus\Http\Server\Kubernetes\Helm;

/**
 * This class is generated by mammatus/http-server, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class ServerValues implements \WyriHaximus\Broadcast\Contracts\Listener
{
    public function values(\Mammatus\Kubernetes\Events\Helm\Values $values): void
    {
        $values->addToGroup(
            new \Mammatus\Groups\Attributes\Group(\Mammatus\Groups\Type::Daemon, 'frontend'),
            [
                [
                    'helper' => 'mammatus.container.port',
                    'type' => 'container',
                    'arguments' => [
                        'name' => 'frontend',
                        'containerPort' => 1337,
                    ],
                ],
                ],
        );
        $values->addToGroup(
            new \Mammatus\Groups\Attributes\Group(\Mammatus\Groups\Type::Daemon, 'healthz'),
            [
                [
                    'helper' => 'mammatus.container.port',
                    'type' => 'container',
                    'arguments' => [
                        'name' => 'healthz',
                        'containerPort' => 9666,
                    ],
                ],
                                [
                    'helper' => 'mammatus.container.probe',
                    'type' => 'container',
                    'arguments' => [
                    'liveness' => [
                            'path' => '/probe/liveness',
                            'vhost' => 'healthz',
                        ],
                    'readiness' => [
                            'path' => '/probe/readiness',
                            'vhost' => 'healthz',
                        ],
                    'startUp' => [
                            'path' => '/probe/startup',
                            'vhost' => 'healthz',
                        ],
                    ],
                ],
            ],
        );
        foreach (\Mammatus\Groups\Groups::lookUpNormalFor('frontend') as $group) {
            $values->add(
                new \Mammatus\Kubernetes\Events\Helm\Values\Registry\Service(
                    'frontend',
                    $group,
                    1337,
                ),
            );
        }
        }
}
